
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-config-template
  labels:
    app.kubernetes.io/name: {{ include "temporal.name" $ }}
    helm.sh/chart: {{ include "temporal.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
data:
{{ (tpl (.Files.Glob "configs/config_template.yaml").AsConfig . )| indent 2 }}